### ISSUE TITLE
Any Contribution?

### ISSUE THREAD

**Issue by Ghislain1** [RenanBezerraEnes/DatingApp#1]
Hi Renan,
I use C# over 5 years and i want to contribute any projects.. 
let me know if we can work together

**Comment by RenanBezerraEnes** [comment]
Hi Ghislain,

Nice to meet you.
Sure this is just a personal project, but we could have a chat and get to know each other.
I couldn't find your linkedIn link on your page, please add me https://www.linkedin.com/in/renanbezerra/

**Comment by Ghislain1** [comment]
Thank you for feedback
Sure  we can have a chat..
I m at home now and i send you a request friend from Linkedin..
